server_port: "8080"
grpc_server_port: "51005"
executor_service_address: "executor-service:50051"
company_auth_address: "company-auth-service:50052"

logging:
  level: "info"
  environment: "production"